version: '2.1'

services:

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: 'test'
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
    ports:
      - "5432:5432"

  app:
    build: .
    network_mode: host
    depends_on:
      - db